"""
hdbscan_clustering.py
Clusters entities using HDBSCAN based on behavioral features.
Identifies common transaction profiles and correlates clusters with anomaly scores.
"""

import os
import sys
import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.preprocessing import StandardScaler

# Try importing from original hdbscan library; fall back to scikit-learn's HDBSCAN
try:
    import hdbscan
    HDBSCAN_Class = hdbscan.HDBSCAN
except ImportError:
    from sklearn.cluster import HDBSCAN as HDBSCAN_Class

# Ensure backend packages can be imported
REPO_ROOT = Path(__file__).resolve().parents[4]
sys.path.append(str(REPO_ROOT))

class TransactionClusteredModel:
    """
    Wrapper for HDBSCAN clustering model.
    """
    
    def __init__(self, min_cluster_size: int = 10, min_samples: int = 10):
        # min_cluster_size: The minimum size of a group of points to be considered a cluster.
        # min_samples: The number of samples in a neighborhood for a point to be considered a core point.
        self.model = HDBSCAN_Class(
            min_cluster_size=min_cluster_size,
            min_samples=min_samples
        )
        self.scaler = StandardScaler()
        
    def fit_predict(self, X: pd.DataFrame) -> np.ndarray:
        """
        Standardizes features and predicts cluster labels.
        
        Short Explanations:
        - Why scale features first:
          HDBSCAN uses distance metrics (typically Euclidean distance) to compute core distances and density.
          If we do not scale, features with larger ranges (e.g. avg_inter_arrival_time which goes up to 25700) 
          would dominate features with smaller scales (e.g. betweenness_centrality in [0, 0.04]), rendering 
          the smaller features useless in distance calculations.
          
        - fit_predict():
          Combines the fit (learning the hierarchical clustering tree and finding core points) 
          and predict (extracting clusters based on stability and assigning cluster labels) steps.
        """
        # Standardize features (mean=0, variance=1)
        X_scaled = self.scaler.fit_transform(X)
        
        # Fit and predict labels
        labels = self.model.fit_predict(X_scaled)
        return labels

def main():
    REPO_ROOT = Path(__file__).resolve().parents[4]
    scores_path = str(REPO_ROOT / "data" / "dev" / "anomaly_scores.parquet")
    output_path = str(REPO_ROOT / "data" / "dev" / "cluster_labels.parquet")
    
    if not os.path.exists(scores_path):
        print(f"Error: anomaly_scores.parquet not found at {scores_path}. Run anomaly detection first.")
        sys.exit(1)
        
    print(f"Loading anomaly scores from {scores_path}...")
    df = pd.read_parquet(scores_path)
    
    # ----------------------------------------------------
    # Why we exclude anomaly_score from clustering input:
    # anomaly_score is a meta-feature generated by the Isolation Forest model. 
    # If we include it, it will dominate density calculations, forcing HDBSCAN to group 
    # points based on their "anomaly status" instead of finding natural behavioral patterns. 
    # Keeping it separate allows unbiased clustering and clean post-hoc correlation.
    # ----------------------------------------------------
    feature_cols = [col for col in df.columns if col != "anomaly_score"]
    X = df[feature_cols]
    
    print(f"Clustering {X.shape[0]} entities with HDBSCAN (min_cluster_size=10, min_samples=10)...")
    clusterer = TransactionClusteredModel(min_cluster_size=10, min_samples=10)
    labels = clusterer.fit_predict(X)
    
    # Add cluster_id column
    result_df = df.copy()
    result_df["cluster_id"] = labels
    
    # Save output
    print(f"Saving clustered entities to Parquet at {output_path}...")
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    result_df.to_parquet(output_path)
    
    # Analyze clusters
    unique_labels = set(labels)
    # -1 represents noise, other non-negative integers represent valid clusters
    num_clusters = len([lab for lab in unique_labels if lab != -1])
    num_noise = int((labels == -1).sum())
    
    print("\n--- CLUSTERING STATISTICS ---")
    print(f"Total number of valid clusters found: {num_clusters}")
    print(f"Number of entities labeled as noise (-1): {num_noise}")
    
    # Group by showing average anomaly_score per cluster
    groupby_stats = result_df.groupby("cluster_id").agg(
        entity_count=("anomaly_score", "count"),
        avg_anomaly_score=("anomaly_score", "mean"),
        max_anomaly_score=("anomaly_score", "max")
    ).sort_values(by="avg_anomaly_score", ascending=False)
    
    print("\nCluster Profiling (sorted by highest average anomaly score):")
    print(groupby_stats.to_string())
    
    print("\nClustering execution completed.")

if __name__ == "__main__":
    main()
